from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path


MANIFEST_DIR = ".pdf-genesis"
MANIFEST_FILE = "manifest.json"


@dataclass
class CompileConfig:
    include_globs: list[str] = field(
        default_factory=lambda: ["README.md", "docs/**/*.md", "papers/*.md"]
    )
    exclude: list[str] = field(default_factory=list)
    figures_glob: str = "exports/figures/*.png"
    exports: list[str] = field(default_factory=list)
    output: str = "papers/Repo_Compendium.pdf"


@dataclass
class RepoManifest:
    root: Path
    version: int = 1
    title: str = "Repository Research Report"
    subtitle: str = ""
    author: str = ""
    organization: str = ""
    paper_mode: str = "research"
    pipeline: str | None = None
    builder: str | None = None
    output: str | None = None
    compile: CompileConfig = field(default_factory=CompileConfig)
    footer: str = "Generated by pdf-genesis"


def manifest_path(repo_root: Path) -> Path:
    return repo_root / MANIFEST_DIR / MANIFEST_FILE


def load_manifest(repo_root: Path) -> RepoManifest:
    repo_root = repo_root.resolve()
    path = manifest_path(repo_root)
    if path.exists():
        data = json.loads(path.read_text(encoding="utf-8"))
        compile_raw = data.get("compile") or {}
        compile_cfg = CompileConfig(
            include_globs=compile_raw.get(
                "include_globs",
                ["README.md", "docs/**/*.md", "papers/*.md"],
            ),
            exclude=list(compile_raw.get("exclude", [])),
            figures_glob=compile_raw.get("figures_glob", "exports/figures/*.png"),
            exports=list(compile_raw.get("exports", [])),
            output=compile_raw.get("output", "papers/Repo_Compendium.pdf"),
        )
        return RepoManifest(
            root=repo_root,
            version=int(data.get("version", 1)),
            title=data.get("title", repo_root.name),
            subtitle=data.get("subtitle", ""),
            author=data.get("author", ""),
            organization=data.get("organization", ""),
            paper_mode=data.get("paper_mode", "research"),
            pipeline=data.get("pipeline"),
            builder=data.get("builder"),
            output=data.get("output"),
            compile=compile_cfg,
            footer=data.get("footer", "Generated by pdf-genesis"),
        )
    return default_manifest(repo_root)


def default_manifest(repo_root: Path) -> RepoManifest:
    return RepoManifest(
        root=repo_root.resolve(),
        title=f"{repo_root.name} — Research Compendium",
        compile=CompileConfig(),
    )
