"""Report generation configuration."""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field


ThemeName = Literal["lab_white", "chorus_dark"]


class ReportConfig(BaseModel):
    title: str = "Research Report"
    author: str = "pdf-genesis"
    organization: str = "CHORUS Research"
    theme: ThemeName = "lab_white"
    page_size: Literal["letter", "a4"] = "letter"
    include_cover: bool = True
    include_toc: bool = True
    include_page_numbers: bool = True
    logo_path: Path | None = None
    footer_text: str = "Confidential — generated by pdf-genesis"
    margin_inch: float = 0.85

    model_config = {"arbitrary_types_allowed": True}
